/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as PalsIndexRouteImport } from './routes/pals/index'
import { Route as PalsPalIdRouteImport } from './routes/pals/$palId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const PalsIndexRoute = PalsIndexRouteImport.update({
  id: '/pals/',
  path: '/pals/',
  getParentRoute: () => rootRouteImport,
} as any)
const PalsPalIdRoute = PalsPalIdRouteImport.update({
  id: '/pals/$palId',
  path: '/pals/$palId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/pals/$palId': typeof PalsPalIdRoute
  '/pals/': typeof PalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/pals/$palId': typeof PalsPalIdRoute
  '/pals': typeof PalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/pals/$palId': typeof PalsPalIdRoute
  '/pals/': typeof PalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/items' | '/pals/$palId' | '/pals/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/items' | '/pals/$palId' | '/pals'
  id: '__root__' | '/' | '/items' | '/pals/$palId' | '/pals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsRoute: typeof ItemsRoute
  PalsPalIdRoute: typeof PalsPalIdRoute
  PalsIndexRoute: typeof PalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pals/': {
      id: '/pals/'
      path: '/pals'
      fullPath: '/pals/'
      preLoaderRoute: typeof PalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pals/$palId': {
      id: '/pals/$palId'
      path: '/pals/$palId'
      fullPath: '/pals/$palId'
      preLoaderRoute: typeof PalsPalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsRoute: ItemsRoute,
  PalsPalIdRoute: PalsPalIdRoute,
  PalsIndexRoute: PalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
